project:
  type: website
  output-dir: _site
  resources:
    - fun.js
    - mathematician.js
    - images/**

website:
  title: "SIAM @ IIT"
  navbar: false

format:
  html:
    theme: none
    css: styles.css
    toc: false
    smooth-scroll: true

execute:
  freeze: auto

metadata-files:
  - chapter-links.yml